### ISSUE TITLE
Login with bcrypt

### ISSUE THREAD

**Issue by Gogadon** [BcryptNet/bcrypt.net#119] opened 2022-09-11 15:58 UTC
Hello all,
I have a question and we try to use the login of our forum (WoltLab) for a GameServer login (C#) that has worked with the old version of WoltLab only with the update they have changed something in the Bcrypt! 
before the passwords in the database looked like this
Example
"$2a$08$0sfiFPeemEZO8EvbSaB8Vul2z0EgvaFdURVym575YH1Vth2vq8fsO"
Now they look like this
Example
"Bcrypt:$2y$12$Y7LETq.zS/D1DqYlh4I6beRvX8nF/VEJKnjOLGz6d9.jJKleH.d0a"

our code before how we did the login
```
using System;
using BCryptNet = BCrypt.Net.BCrypt;

public class BCryptTest
{
	public static void Main(string[] args)
	{
		String password = "root";
		String passwordHash = "$2a$08$2wPUa90rOBr8ok9t99f0deDdWeLwDSfOPntJjR.cN2ntlm2DR9wxq";
		String hash = BCryptNet.HashPassword(BCryptNet.HashPassword(password, passwordHash), passwordHash);
			Console.WriteLine(hash);

		if (BCryptNet.Equals(hash, passwordHash))
			Console.WriteLine("password ok");
		else
			Console.WriteLine("password wrong");
	}
}
```

what we had tried now
```
using System;
using BCryptNet = BCrypt.Net.BCrypt;

public class BCryptTest
{
	public static void Main(string[] args)
	{
		String password = "WjswE$v?(n2/";
		String passwordHash = "Bcrypt:$2y$12$Y7LETq.zS/D1DqYlh4I6beRvX8nF/VEJKnjOLGz6d9.jJKleH.d0a".Replace("Bcrypt:", ""); // <-- Replace
		String hash = BCryptNet.HashPassword(BCryptNet.HashPassword(password, passwordHash), passwordHash);
			Console.WriteLine(hash);

		if (BCryptNet.Equals(hash, passwordHash))
			Console.WriteLine("password ok");
		else
			Console.WriteLine("password wrong");
	}
}
```

With .NET 4.7.2 & BCrypt.net (https://dotnetfiddle.net/W1XDt5)
With .NET 6 & BCrypt.NET-Next (https://dotnetfiddle.net/YUnMby)

Only we always get a password wrong out !
Can someone help?

**Comment by ChrisMcKee** [comment] 2022-09-12 11:37
I wrote an entire thing based on it being BCrypt but on re-looking at your example it clicked that you're double hashing; which provides zero actual security benefit in this instance or the WCF setup as the SALT remains the same... its an inconvenience rather than security.

A lot of what I wrote before the coffee kicked in still stands; but I'll break down your issue in bullet points so I don't miss anything

* The hash you've provided me in the example is marked as `Bcrypt:` in the WCF codebase that will select the normal [BCrypt password class](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Bcrypt.class.php) via the password manager. 
The code you've used is based on their [double-bcrypt class](https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/user/authentication/password/algorithm/DoubleBcrypt.class.php)

I've added test coverage with extra comments based on php generated hashes using double-bcrypt (using the built in php bcrypt module)
https://github.com/BcryptNet/bcrypt.net/blob/533eee3fcf1dbd4a61300d2c36adecdd6734e068/src/BCrypt.Net.UnitTests/BCryptTests.cs#L132-L169

Essentially it becomes

`BCrypt.Verify(BCrypt.HashPassword(UsersPassword, ExistingHash), ExistingHash)`

It does work against the PHP version; though I'd advise utilising the forums password manager and using standard BCrypt and increasing the cost if you want higher protection; doubling the call is pointless.

Hope that helps

Chris



---

Based on before example 

```php
<?php 
$hash = '$2a$08$2wPUa90rOBr8ok9t99f0deDdWeLwDSfOPntJjR.cN2ntlm2DR9wxq';

if (password_verify('root', $hash)) {
    echo 'Password is valid!';
} else {
    echo 'Invalid password.';
}
?>
```

![image](https://user-images.githubusercontent.com/83597/189616924-cc040df7-72db-4451-bcf5-7bc7b1dd01e0.png)
![image](https://user-images.githubusercontent.com/83597/189618122-3c96a11d-bd3e-4b32-93e1-293f0969db87.png)
![image](https://user-images.githubusercontent.com/83597/189618155-91e60c3a-8144-4b5c-b6de-5c4dbcfc5972.png)



The "after" works.

![image](https://user-images.githubusercontent.com/83597/189617172-b10e8115-22d9-407d-8f9d-9eff9682e25a.png)
![image](https://user-images.githubusercontent.com/83597/189618553-a85da5b1-3be9-4ebe-9154-805588cce5fd.png)


There is some _interesting_ code in that forum repo though which may be the cause of the issue; 
it would be helpful to check which version your data was hashed in as I _think_ they've basically added the prefix to ensure that they can roll forwards. But I imagine it depends on which of the "interesting" security options they have has been selected.


I'm assuming you're using the default password manager option which is BCrypt `https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/user/authentication/password/algorithm/Bcrypt.class.php` (and not some of those iffy other options like DoubleBCrypt)

The code here (thankfully) seems to just call the underlying php implementation which I've shown above validated.

The prefix they're passing; as with your change is being replaced on the fly (sort of)
https://github.com/WoltLab/WCF/blob/a43293b3c5070d08ab8396cafd896771991f4e75/wcfsetup/install/files/lib/data/user/UserEditor.class.php#L60

They're taking the password and using the manager to work out what prefix to append on creation using the class name. 

In the `checkPassword` function  (assuming I'm in the right one as I'm relying on github ref/dep options (https://github.com/WoltLab/WCF/blob/a43293b3c5070d08ab8396cafd896771991f4e75/wcfsetup/install/files/lib/util/PasswordUtil.class.php#L103) they're fetching the "encryption" (hash) type as a string then sub-stringing the raw-hash to remove the `TYPE:` prefix (the detect method also substrings).

**Closed** 2022-09-16 19:02 UTC
Labels: question
